### ISSUE TITLE
What is the meaning of data features and target variables?

### ISSUE THREAD

**Issue by YaoXiao-CS** [gagolews/teaching_data#1]
Hello, I am currently conducting research on **ordinal regression and deep learning**, and I would like to understand the significance of this dataset. Can you provide that? Or is there any related paper on this dataset? The link is [cement_strength.csv](https://raw.githubusercontent.com/gagolews/ordinal_regression_data/master/cement_strength.csv).

**Comment by gagolews** [comment]
Please refer to: <https://archive.ics.uci.edu/dataset/165/concrete+compressive+strength>

**Comment by YaoXiao-CS** [comment]
Thanks for your response.
